spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: JobPortalHikariPool
      leak-detection-threshold: 60000
      validation-timeout: 5000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: false

logging:
  level:
    root: INFO
    org.springdoc: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN