spring:
  datasource:
    url: jdbc:postgresql://100.76.150.8:5432/jobportal?timeZone=UTC
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:jobportal123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 600000
      pool-name: JobPortalHikariPool
      leak-detection-threshold: 60000
      validation-timeout: 5000
      connection-test-query: SELECT 1
      auto-commit: true
      data-source-properties:
        prepareThreshold: 0
        preparedStatementCacheQueries: 0

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:tryaac1ss@gmail.com}
    password: ${MAIL_PASSWORD:acxf frwi bjfo ibas}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: false

logging:
  level:
    org.springdoc: INFO
    org.hibernate.type: WARN