spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.geqlzcvxpshycmfahdcw&password=%40Ashishthapa46&sslmode=require
    username: postgres
    password: '@Ashishthapa46'
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 600000
      pool-name: JobPortalHikariPool
      leak-detection-threshold: 60000
      validation-timeout: 5000
      connection-test-query: SELECT 1
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: tryaac1ss@gmail.com
    password: "acxf frwi bjfo ibas"
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

springdoc:
  packages-to-scan: com.jobportal.v1.controller
  paths-to-match: /api/**