name: Deploy Backend to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: aac1ss
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /mnt/storage/server/compose

            echo "Stopping old container..."
            docker compose -f backend.yml down || true

            echo "Building and starting new container..."
            docker compose -f backend.yml up -d --build

            echo "Deployment complete "
